version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=jazzba-db
    ports:
      - 5432:5432
    command: ["-c", "log_statement=all"]
  mq:
    image: rabbitmq
    environment: 
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
  se:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node