// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ztimes2/jazzba/pkg/storage (interfaces: NoteStore)

// Package mock is a generated GoMock package.
package mock

import (
	gomock "github.com/golang/mock/gomock"
	storage "github.com/ztimes2/jazzba/pkg/storage"
	reflect "reflect"
)

// NoteStore is a mock of NoteStore interface
type NoteStore struct {
	ctrl     *gomock.Controller
	recorder *NoteStoreMockRecorder
}

// NoteStoreMockRecorder is the mock recorder for NoteStore
type NoteStoreMockRecorder struct {
	mock *NoteStore
}

// NewNoteStore creates a new mock instance
func NewNoteStore(ctrl *gomock.Controller) *NoteStore {
	mock := &NoteStore{ctrl: ctrl}
	mock.recorder = &NoteStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *NoteStore) EXPECT() *NoteStoreMockRecorder {
	return m.recorder
}

// BeginTx mocks base method
func (m *NoteStore) BeginTx() (storage.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx")
	ret0, _ := ret[0].(storage.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx
func (mr *NoteStoreMockRecorder) BeginTx() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*NoteStore)(nil).BeginTx))
}

// CreateOne mocks base method
func (m *NoteStore) CreateOne(arg0 storage.CreateNoteParameters) (*storage.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOne", arg0)
	ret0, _ := ret[0].(*storage.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOne indicates an expected call of CreateOne
func (mr *NoteStoreMockRecorder) CreateOne(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOne", reflect.TypeOf((*NoteStore)(nil).CreateOne), arg0)
}

// DeleteOne mocks base method
func (m *NoteStore) DeleteOne(arg0 storage.Tx, arg1 int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOne", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOne indicates an expected call of DeleteOne
func (mr *NoteStoreMockRecorder) DeleteOne(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOne", reflect.TypeOf((*NoteStore)(nil).DeleteOne), arg0, arg1)
}

// FetchAllPaginated mocks base method
func (m *NoteStore) FetchAllPaginated(arg0, arg1 int) ([]storage.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchAllPaginated", arg0, arg1)
	ret0, _ := ret[0].([]storage.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchAllPaginated indicates an expected call of FetchAllPaginated
func (mr *NoteStoreMockRecorder) FetchAllPaginated(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchAllPaginated", reflect.TypeOf((*NoteStore)(nil).FetchAllPaginated), arg0, arg1)
}

// FetchMany mocks base method
func (m *NoteStore) FetchMany(arg0 []int) ([]storage.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchMany", arg0)
	ret0, _ := ret[0].([]storage.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchMany indicates an expected call of FetchMany
func (mr *NoteStoreMockRecorder) FetchMany(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchMany", reflect.TypeOf((*NoteStore)(nil).FetchMany), arg0)
}

// FetchManyByNotebookPaginated mocks base method
func (m *NoteStore) FetchManyByNotebookPaginated(arg0, arg1, arg2 int) ([]storage.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchManyByNotebookPaginated", arg0, arg1, arg2)
	ret0, _ := ret[0].([]storage.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchManyByNotebookPaginated indicates an expected call of FetchManyByNotebookPaginated
func (mr *NoteStoreMockRecorder) FetchManyByNotebookPaginated(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchManyByNotebookPaginated", reflect.TypeOf((*NoteStore)(nil).FetchManyByNotebookPaginated), arg0, arg1, arg2)
}

// FetchManyByNotebooks mocks base method
func (m *NoteStore) FetchManyByNotebooks(arg0 []int) (storage.NotebookNotesMap, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchManyByNotebooks", arg0)
	ret0, _ := ret[0].(storage.NotebookNotesMap)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchManyByNotebooks indicates an expected call of FetchManyByNotebooks
func (mr *NoteStoreMockRecorder) FetchManyByNotebooks(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchManyByNotebooks", reflect.TypeOf((*NoteStore)(nil).FetchManyByNotebooks), arg0)
}

// FetchOne mocks base method
func (m *NoteStore) FetchOne(arg0 int) (*storage.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FetchOne", arg0)
	ret0, _ := ret[0].(*storage.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchOne indicates an expected call of FetchOne
func (mr *NoteStoreMockRecorder) FetchOne(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchOne", reflect.TypeOf((*NoteStore)(nil).FetchOne), arg0)
}

// UpdateOne mocks base method
func (m *NoteStore) UpdateOne(arg0 storage.UpdateNoteParameters) (*storage.Note, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateOne", arg0)
	ret0, _ := ret[0].(*storage.Note)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateOne indicates an expected call of UpdateOne
func (mr *NoteStoreMockRecorder) UpdateOne(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateOne", reflect.TypeOf((*NoteStore)(nil).UpdateOne), arg0)
}
